#!/usr/bin/env bash

cd "$(dirname "$0")"

mkdir -p "build" "download"

printf -v rx "|%s" \
       "Jan" "January" \
       "Feb" "February" \
       "Mar" "March" \
       "Apr" "April" \
       "May" \
       "Jun" "June" \
       "Jul" "July" \
       "Aug" "August" \
       "Sep" "September" \
       "Oct" "October" \
       "Nov" "November" \
       "Dec" "December" \
       "Mid" "Fall" "Spring"

rx="(((${rx:1}) )?(19[89]|2[0-2][0-2])[0-9]|Present)"
rx="$rx( ?[-–—]+ ?$rx)?"
extract_dates() {
  grep -woE "$rx" "$1"
}

md_to_text() {
  I="$1" O="$2" node -e '
    fs.writeFileSync(process.env.O,
      fs.readFileSync(process.env.I).toString()
        .replaceAll(/(?<=^|\n\n)(#+) +(.*)(?=\n)/g, (_, h, s) =>
          s+"\n"+(h.length <= 2 ? "=" : "-").repeat(s.length))
        .replaceAll(/ +\\\n/g, "\n")
        .replaceAll(/<(https?:\/\/[^<>]+|[^<>@]+@[^<>@]+)>/g, "$1")
        .replaceAll(/\*("[^"]+")\*/g, "$1"));
  '
}

cat > "build/latex-tweaks.sty" <<EOF
\urlstyle{tt}
\usepackage{inconsolata}
EOF

for what in "long" "short"; do
  echo "$what..."
  out="download/Eli_Barzilay-$what"
  ####
  md="build/$what.md"
  ./cv.rkt "$what" "md" > "$md.new" || exit 1
  if grep -qE ".{80}" "$md.new"; then
    echo "Error: got lines over 80 chars in $md.new" 1>&2; exit 1
  fi
  if [[ ! -e "$md" ]]; then
    echo "Created $md"
    mv "$md.new" "$md"
  elif ! diff "$md" "$md.new"; then
    echo ""
    echo "Markdown changes in $md.new"
    echo "* Remove \"$md\" or update from \"$md.new\""
    echo "* Re-run"
    exit 1
  else
    rm "$md.new"
  fi
  ####
  dates="build/dates-$what"
  extract_dates "$md" > "$dates.new" || exit 1
  if [[ ! -e "$dates" ]]; then
    echo "Created $dates"
    mv "$dates.new" "$dates"
  elif ! diff "$dates" "$dates.new"; then
    echo ""
    echo "Date changes in $md"
    echo "* Update the data in \"dates.js\""
    echo "* Remove \"$dates\" or update from \"$dates.new\""
    echo "* Re-run"
    exit 1
  else
    rm "$dates.new"
  fi
  ####
  args=(-f commonmark+smart "$md")
  args+=(-M author="Eli Barzilay")
  args+=(-M title="Eli Barzilay: Curriculum Vitae")
  args+=(-M date="$(date --iso-8601)")
  args+=(-M papersize="letter")
  args+=(-M fontfamily="FiraSans")
  args+=(-M fontfamilyoptions="sfdefault")
  args+=(-H "build/latex-tweaks.sty")
  # pandoc -s "${args[@]}" -o "$out.tex"
  pandoc --pdf-engine=pdflatex "${args[@]}" -o "$out.pdf" || exit 1
  pandoc "${args[@]}" -o "$out.docx" || exit 1
  md_to_text "$md" "$out.txt" || exit 1
done

echo "done"
