#!/usr/bin/env bash

cd "$(dirname "$0")"
here="$PWD"

mkdir -p "build" "download"

check() {
  local f="$1"; shift
  if [[ ! -s "$f" ]]; then
    echo "Created $f"
    mv -f "$f.new" "$f"
  elif ! diff "$f" "$f.new"; then
    echo ""
    echo "Changes in $f.new"
    echo "* Remove \"$f\" or manually update from \"$f.new\""
    echo "* Re-run"
    exit 1
  else
    rm "$f.new"
  fi
}

run_check() { # output cmd ...
  local out="$1"; shift
  "$@" > "$out.new" || exit 1
  check "$out"
}

run_check_wrap() {
  run_check "$@"
  if ! grep -qE ".{80}" "$1"; then return; fi
  echo "Error: got lines over 80 chars in $1" 1>&2; exit 1
}

for what in long short; do
  echo "$what..."
  out="download/Eli_Barzilay-$what"
  build="build/$what"
  #### MD
  md="$build.md"
  run_check "$md" ./cv.rkt $what md
  md_fmt=commonmark+smart
  #### HTML
  pandoc -f $md_fmt -t html "$md" -o "$build.html"
  #### TXT
  if [[ $what = long ]]; then df="build/dates.js"; else df=""; fi
  dates_file="$df" \
    run_check_wrap "$out.txt" ./cv.rkt $what md text
  #### PDF
  tex="$build.tex"
  run_check "$tex" ./cv.rkt $what tex
  ln -sf "../acv/awesome-cv.cls" "../acv/fonts" "build"
  args=(--halt-on-error --interaction="nonstopmode")
  args+=("../$tex")
  # twice to get a TOC, show nothing on first run, warnings on the second run
  (cd "build"; xelatex "${args[@]}") > "/tmp/xelatex-log" \
    || { cat "/tmp/xelatex-log"; exit 1; }
  (cd "build"; xelatex "${args[@]}") \
    | awk 'BEGIN{IGNORECASE=1} /warning|!/{show=1} /^$/{show=0} show;' \
    | { grep -v 'Package floatflt Warning: Floating figures .* colliding' \
          || test $? = 1; } \
    || exit 1
  rm -f "$build."{"aux","out","log"}
  rm -f "build/"{"texput.log","awesome-cv.cls","fonts"}
  mv "$build.pdf" "$out.pdf"
  #### DOCX
  args=(-s)
  # args+=(-M author="Eli Barzilay")
  args+=(-M title="Eli Barzilay: Curriculum Vitae")
  # args+=(-M date="2021-12-31")
  args+=(-M papersize="letter")
  args+=(--resource-path="$here/acv/fonts")
  # args+=(-M fontfamily="FiraSans")
  # args+=(-M fontfamilyoptions="default")
  # args+=(-V "mainfont:FiraSans")
  # args+=(-V "sansfont:FiraSans")
  # args+=(-V "monofont:Consolas")
  if [[ -e "$out.docx" ]]; then cp "$out.docx" "build/ref.docx"; fi
  args+=(--reference-doc="build/ref.docx")
  # pandoc -f $md_fmt "$md""${args[@]}" -o "$tex"
  args+=(--pdf-engine="xelatex")
  pandoc -f $md_fmt "$md" "${args[@]}" -o "$out.docx" || exit 1
  # pandoc -f latex "$tex" "${args[@]}" -o "$out.docx" || exit 1
  rm -f "build/ref.docx"
done

echo "done"
